#!/usr/bin/env python3
"""Reusable PDF style loader, validator and ReportLab adapter.

Presentation only: content semantics remain owned by the requesting workflow.
"""
from __future__ import annotations
import argparse, json
from pathlib import Path
import jsonschema
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4, LETTER, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted, Table, TableStyle

ROOT = Path(__file__).resolve().parents[1]
STYLE_DIR = ROOT / "pdf_styles"
STYLE_SCHEMA = ROOT / "pdf_style_schema.json"
BUILTIN_FONTS = {"Helvetica","Helvetica-Bold","Helvetica-Oblique","Helvetica-BoldOblique","Courier","Courier-Bold","Courier-Oblique","Courier-BoldOblique","Times-Roman","Times-Bold","Times-Italic","Times-BoldItalic","Symbol","ZapfDingbats"}
ALIGN = {"left": TA_LEFT, "center": TA_CENTER, "right": TA_RIGHT}
def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def list_styles(root: Path = ROOT) -> list[str]:
    directory = root / "pdf_styles"
    return sorted(p.stem for p in directory.glob("style.pdf.*.json"))


def load_style(style_ref: str, root: Path = ROOT) -> dict:
    candidate = Path(style_ref)
    if not candidate.is_file():
        candidate = root / "pdf_styles" / f"{style_ref}.json"
    if not candidate.is_file():
        raise FileNotFoundError(f"PDF style not found: {style_ref}")
    style = _read_json(candidate)
    schema = _read_json(root / "pdf_style_schema.json")
    jsonschema.validate(style, schema)
    return style


def default_style_id(root: Path = ROOT) -> str:
    cfg = _read_json(root / "manifest.json")
    return cfg["default_style_id"]

def resolve_style(explicit_style: str | None = None, document_style: str | None = None, project_style: str | None = None, root: Path = ROOT) -> dict:
    chosen = explicit_style or document_style or project_style or default_style_id(root)
    return load_style(chosen, root)


def fidelity_audit(style: dict) -> dict:
    fonts = []
    for spec in style.get("typography", {}).values():
        if isinstance(spec, dict) and spec.get("font"):
            fonts.append(spec["font"])
    missing_fonts = sorted({f for f in fonts if f not in BUILTIN_FONTS})
    assets = style.get("assets", {})
    missing_assets = [name for name, path in assets.items() if path and not (ROOT / path).exists()]
    return {
        "status": "EXACT" if not missing_fonts and not missing_assets else "PARTIAL",
        "missing_fonts": missing_fonts,
        "missing_assets": sorted(missing_assets),
    }


def page_settings(style: dict) -> tuple:
    page = style["page"]
    base = {"A4": A4, "LETTER": LETTER}[page["size"]]
    pagesize = landscape(base) if page.get("orientation") == "landscape" else base
    m = page["margins"]
    return pagesize, m["left"], m["right"], m["top"], m["bottom"]

def build_paragraph_styles(style: dict) -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    palette = style["palette"]
    out = {}
    for key, spec in style["typography"].items():
        parent = base["Code"] if key == "code" else base["Normal"]
        out[key] = ParagraphStyle(
            name=f"PDFStyler_{key}", parent=parent,
            fontName=spec["font"], fontSize=spec["size"], leading=spec["leading"],
            textColor=colors.HexColor(spec.get("color", palette["text"])),
            alignment=ALIGN.get(spec.get("align", "left"), TA_LEFT),
            leftIndent=spec.get("left_indent", 0), rightIndent=spec.get("right_indent", 0),
            spaceBefore=0, spaceAfter=0,
            backColor=colors.HexColor(spec["background"]) if spec.get("background") else None,
            borderColor=colors.HexColor(spec["border_color"]) if spec.get("border_color") else None,
            borderWidth=spec.get("border_width", 0), borderPadding=spec.get("padding", 0),
        )
    return out


def style_metadata(style: dict) -> dict:
    audit = fidelity_audit(style)
    return {"style_id": style["id"], "style_version": style["version"], "fidelity": audit}

def render_specimen(output: Path, style: dict) -> Path:
    pagesize, left, right, top, bottom = page_settings(style)
    styles = build_paragraph_styles(style)
    doc = SimpleDocTemplate(str(output), pagesize=pagesize,
                            leftMargin=left, rightMargin=right, topMargin=top, bottomMargin=bottom)
    gap = style["spacing"].get("base_gap", 12)
    story = [
        Paragraph("PDF Styler Specimen", styles["title"]), Spacer(1, gap),
        Paragraph(f"Active preset: {style['id']}", styles["subtitle"]), Spacer(1, gap * 2),
        Paragraph("Heading One", styles["heading_1"]), Spacer(1, gap),
        Paragraph("This page is generated by the reusable PDF Styler adapter. Content remains independent from presentation; the preset controls typography, page geometry, colour and component treatment.", styles["body"]),
        Spacer(1, gap * 1.5), Paragraph("Heading Two", styles["heading_2"]), Spacer(1, gap),
        Preformatted("style = resolve_style()\nrender_pdf(content, style)", styles["code"]), Spacer(1, gap * 1.5),
    ]
    table = Table([["Token", "Example"], ["Text", style["palette"]["text"]], ["Muted", style["palette"]["muted"]]], colWidths=[110, 240])
    table.setStyle(TableStyle([("GRID", (0,0), (-1,-1), 0.5, colors.HexColor(style["palette"]["line"])),
                               ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"), ("FONTSIZE", (0,0), (-1,-1), 9),
                               ("TEXTCOLOR", (0,0), (-1,-1), colors.HexColor(style["palette"]["text"])),
                               ("LEFTPADDING", (0,0), (-1,-1), 7), ("RIGHTPADDING", (0,0), (-1,-1), 7)]))
    story += [table]
    doc.build(story)
    return output

def main() -> int:
    ap = argparse.ArgumentParser(description="Resolve and validate reusable PDF styles")
    ap.add_argument("--style", help="Style id or JSON path")
    ap.add_argument("--list", action="store_true", help="List registered PDF styles")
    ap.add_argument("--show", action="store_true", help="Print resolved style JSON")
    ap.add_argument("--validate", action="store_true", help="Validate style and print fidelity audit")
    ap.add_argument("--specimen", help="Render a specimen PDF to this path")
    args = ap.parse_args()
    if args.list:
        print("\n".join(list_styles()))
        return 0
    style = resolve_style(args.style)
    if args.show:
        print(json.dumps(style, indent=2, ensure_ascii=False))
    if args.validate:
        print(json.dumps(style_metadata(style), indent=2, ensure_ascii=False))
    if args.specimen:
        print(render_specimen(Path(args.specimen), style))
    if not (args.show or args.validate or args.specimen):
        print(style["id"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
